@devUrl = http://localhost:8000/api
@prodUrl = https://xamify.herokuapp.com/api

@baseUrl = {{prodUrl}}
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHhhbWlmeS5jb20iLCJ0eXBlIjoiVEVBQ0hFUiIsImlhdCI6MTYzMjE3Mjc3NiwiZXhwIjoxNjMyMTczNjc2fQ.16L8b5i4IqkIX0S6GPUOgVLJB2sF-4uaWdIjGYqg5-k
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHhhbWlmeS5jb20iLCJ0eXBlIjoiVEVBQ0hFUiIsImlhdCI6MTYzMjE0NTI1MSwiZXhwIjoxNjMyNzUwMDUxfQ.52bXR1cKstOmmNamTuFE-udf9YeTJqv8cfifqZ71E7w


###
// PING SERVER
GET {{baseUrl}}/ping

###
// CREATE DEFAULT TEACHER
GET {{baseUrl}}/auth/multiverse

###
// LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"admin@xamify.com",
    "password":"zLnNe7tYh^uvH#Qi"
}

###
// GET CURRENT USER DETAILS
GET {{baseUrl}}/auth/me 
Authorization:  {{token}}

###
// REFRESH TOKEN
POST {{baseUrl}}/auth/token 
Content-Type: application/json

{
    "token":"{{refresh}}"
}

###
// TEACHERS /api/teachers

// GET ALL TEACHERS
GET {{baseUrl}}/teachers
Authorization: {{token}}

###
// GET SINGLE TEACHER
@teacherid = e2cf9a85-280b-41b8-a534-784e2bc1ef0e
GET {{baseUrl}}/teachers/{{teacherid}}
Authorization: {{token}}

###
// CREATE NEW TEACHER
POST {{baseUrl}}/teachers
Content-Type: application/json
Authorization:  {{token}}

{
    "email":"some@test.com",
    "password":"1234"
}

###
// EDIT SINGLE TEACHER
PATCH {{baseUrl}}/teachers/{{teacherid}}
Content-Type: application/json
Authorization:  {{token}}

{
    "name":"Some Another Teacher"
}

###
// DELETE TEACHER
DELETE  {{baseUrl}}/teachers/{{teacherid}}
Content-Type: application/json
Authorization:  {{token}}


###

// COURSES /api/=courses

// GET ALL COURSES
GET {{baseUrl}}/courses
Authorization: {{token}}

###
// GET SINGLE COUTSE
@courseid = 115ef359-09c6-4da4-abda-cc92fe448156
GET {{baseUrl}}/courses/{{courseid}}
Authorization: {{token}}

###
// CREATE NEW COURSE
POST {{baseUrl}}/courses
Content-Type: application/json
Authorization:  {{token}}

{
    "name": "Mathematics Hons"
}

###
// EDIT COURSE
PATCH {{baseUrl}}/courses/{{courseid}}
Content-Type: application/json
Authorization:  {{token}}

{
    "name":"Mathematics Hons"
}

###
// DELETE COURSE
DELETE  {{baseUrl}}/courses/{{courseid}}
Content-Type: application/json
Authorization:  {{token}}


###

// YEARS /api/years

// GET ALL YEARS
GET {{baseUrl}}/years
Authorization: {{token}}

###
// GET SINGLE YEAR
@yearid = a06ec8a0-8d72-43d7-a6f5-e9625983ce7c
GET {{baseUrl}}/years/{{yearid}}
Authorization: {{token}}

###
// CREATE NEW YEAR
POST {{baseUrl}}/years
Content-Type: application/json
Authorization:  {{token}}

{
    "label": "4th Year"
}

###
// EDIT SINGLE YEAR
PATCH {{baseUrl}}/years/{{yearid}}
Content-Type: application/json
Authorization:  {{token}}

{
    "label":"OP"
}

###
// DELETE YEAR
DELETE  {{baseUrl}}/years/{{yearid}}
Content-Type: application/json
Authorization:  {{token}}


###

// SUBJECTS /api/subjects


// GET ALL SUBJECTS
GET {{baseUrl}}/subjects
Authorization: {{token}}

###
// GET SINGLE SUBJECT
@subjectid = 8fa110f6-6904-4f38-84ef-69f229277770
GET {{baseUrl}}/subjects/{{subjectid}}
Authorization: {{token}}

###
// CREATE NEW SUBJECT
POST {{baseUrl}}/subjects
Content-Type: application/json
Authorization:  {{token}}

{
    "name":"DBMS",
    "yearId":"{{yearid}}",
    "courseId":"{{courseid}}"
}

###
// EDIT SUBJECT
PATCH {{baseUrl}}/subjects/{{subjectid}}
Content-Type: application/json
Authorization:  {{token}}

{
    "name":"Android Programming",
    "yearId":"{{yearid}}",
    "courseId":"{{courseid}}"
}

###
// DELETE SUBJECT
DELETE  {{baseUrl}}/subjects/{{subjectid}}
Content-Type: application/json
Authorization:  {{token}}

###

// STUDENTS /api/students

// GET ALL STUDENTS
GET {{baseUrl}}/students
Authorization: {{token}}

###
// GET SINGLE STUDENT
@studentid = 766dcd01-8e55-4136-9b57-1c1238a50689
GET {{baseUrl}}/students/{{studentid}}
Authorization: {{token}}

###
// CREATE NEW STUDENT
POST {{baseUrl}}/students
Content-Type: application/json
Authorization:  {{token}}

{
    "email":"another@test.com",
    "name": "Some Student",
    "rollNo":"4044",
    "dob":"2001-04-19T12:30:58.000Z",
    "yearId":"{{yearid}}",
    "courseId":"{{courseid}}"
}

###
// EDIT STUDENT
PATCH {{baseUrl}}/students/{{studentid}}
Content-Type: application/json
Authorization:  {{token}}

{
    "name":"Ujjawal"
}

###
// DELETE STUDENT
DELETE  {{baseUrl}}/students/{{studentid}}
Content-Type: application/json
Authorization:  {{token}}


###
// CREATE BULK STUDENTS
POST {{baseUrl}}/students/bulk
Content-Type: application/json
Authorization:  {{token}}

{
    "students": [
        {
            "email":"student1@test.com",
            "name": "Student 1",
            "rollNo":"1011",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student2@test.com",
            "name": "Student 2",
            "rollNo":"1012",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student3@test.com",
            "name": "Student 3",
            "rollNo":"1013",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student4@test.com",
            "name": "Student 4",
            "rollNo":"1014",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student5@test.com",
            "name": "Student 5",
            "rollNo":"1015",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student6@test.com",
            "name": "Student 6",
            "rollNo":"1016",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student7@test.com",
            "name": "Student 7",
            "rollNo":"1017",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student8@test.com",
            "name": "Student 8",
            "rollNo":"1018",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student9@test.com",
            "name": "Student 9",
            "rollNo":"1019",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        },
        {
            "email":"student10@test.com",
            "name": "Student 10",
            "rollNo":"1020",
            "dob":"2001-04-20T12:30:58.000Z",
            "yearId":"{{yearid}}",
            "courseId":"{{courseid}}"
        }
    ]
}

###

// ASSESSMENTS /api/assesments


// GET ALL ASSESSMENTS
GET {{baseUrl}}/assessments
Authorization: {{token}}

###
// GET SINGLE ASSESSMENTS
@assessmentid = 65ce13f5-c977-45b8-8c16-637df3967c95
GET {{baseUrl}}/assessments/{{assessmentid}}
Authorization: {{token}}

###
// CREATE NEW ASSESSMENTS

POST {{baseUrl}}/assessments
Content-Type: application/json
Authorization:  {{token}}

{
    "type": "DIGITAL",
    "subjectId": "{{subjectid}}",
    "startTime": "2021-09-19T17:19:41.376Z",
    "endTime": "2021-09-19T23:19:41.376Z"
}

###
// EDIT ASSESSMENTS
POST {{baseUrl}}/assessments/{{assessmentid}}
Content-Type: application/json
Authorization:  {{token}}

{
    "questions": [
        {
            "type":"MCQ",
            "text":"This is a MCQ Question",
            "choices":[
                {"text":"Option 1"},
                {"text":"Option 2"},
                {"text":"Option 3"},
                {"text":"Option 4"}
            ]
        },
        {
            "type":"TYPE",
            "text":"This is a TYPE Question"
        },
        {
            "type":"IMAGE",
            "text":"This is a IMAGE Question"
        }
    ]
}

###
// DELETE ASSESSMENTS
DELETE  {{baseUrl}}/assessments/{{assessmentid}}
Content-Type: application/json
Authorization:  {{token}}

###